RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: JJGGu/khoj
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: Test
  ConstraintDescription: ''
  Default: sdff
  Name: TEST
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: Test1
  ConstraintDescription: ''
  Default: sdffdff
  Name: TEST22
DockerComposeYamlPath: docker-compose.yml
Owner: JJGGu
Branch: master
Platform: github
