RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: JJGGu/khoj
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
DockerComposeYamlPath: docker-compose.yml
Owner: JJGGu
Branch: master
Platform: github
